/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.CarInfo;
import model.CarsHistory;
import model.Encounter;
import model.EncounterHistory;
import model.Patient;
import model.PatientHistory;

/**
 *
 * @author Admin
 */
public class AddNewAppointment extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    CarsHistory history;
    PatientHistory patienthistory;
    EncounterHistory encounterhistory;
    
    public AddNewAppointment(CarsHistory history,EncounterHistory encounterhistory ,PatientHistory patienthistory) {
        initComponents();
        this.history = history;
        this.patienthistory = patienthistory;
        this.encounterhistory = encounterhistory;
        
        //populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jviewtitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpersondetails = new javax.swing.JTable();
        bttnview = new javax.swing.JButton();
        bttnaddappoint = new javax.swing.JButton();
        jmanufyear = new javax.swing.JLabel();
        jseats = new javax.swing.JLabel();
        jmaintenance = new javax.swing.JLabel();
        jlocation = new javax.swing.JLabel();
        jcarmodel = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblcommunity = new javax.swing.JLabel();
        jpersonid = new javax.swing.JLabel();
        jcity = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jinsurno = new javax.swing.JLabel();
        jdiab = new javax.swing.JLabel();
        jaller = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpatientdetails = new javax.swing.JTable();
        lblpatientid = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblcinsno = new javax.swing.JLabel();
        lbldiab = new javax.swing.JLabel();
        lblall = new javax.swing.JLabel();
        jappointid = new javax.swing.JLabel();
        txtappointid = new javax.swing.JTextField();
        jdate = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jdate1 = new javax.swing.JLabel();
        txtbloodpress = new javax.swing.JTextField();
        txtresprate = new javax.swing.JTextField();
        jdate3 = new javax.swing.JLabel();
        jappointid1 = new javax.swing.JLabel();
        txtheartrate = new javax.swing.JTextField();
        lblbloodpress = new javax.swing.JLabel();
        lblresprate = new javax.swing.JLabel();
        lblheartrate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        jviewtitle.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jviewtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jviewtitle.setText("Add New Appointment");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jviewtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jviewtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblpersondetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Person ID", "Name", "Address", "Age", "Gender", "Community", "City"
            }
        ));
        jScrollPane1.setViewportView(tblpersondetails);

        bttnview.setText("View Details");
        bttnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnviewActionPerformed(evt);
            }
        });

        bttnaddappoint.setText("Add Appointment");
        bttnaddappoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bttnaddappointMousePressed(evt);
            }
        });
        bttnaddappoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnaddappointActionPerformed(evt);
            }
        });

        jmanufyear.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jmanufyear.setText("Address:");

        jseats.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jseats.setText("Age:");

        jmaintenance.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jmaintenance.setText("Gender:");

        jlocation.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jlocation.setText("Community:");

        jcarmodel.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jcarmodel.setText("Name:");

        jpersonid.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jpersonid.setText("Patient ID:");

        jcity.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jcity.setText("City:");

        jButton1.setText("Person Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jinsurno.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jinsurno.setText("Insurance Number:");

        jdiab.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jdiab.setText("Diabetic:");

        jaller.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jaller.setText("Any allergies:");

        tblpatientdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Insurance No.", "Diabetic", "Allergy"
            }
        ));
        jScrollPane2.setViewportView(tblpatientdetails);

        jappointid.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jappointid.setText("Appointment ID:");

        jdate.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jdate.setText("Appointment Date:");

        jdate1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jdate1.setText("Blood Pressure:");

        txtbloodpress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbloodpressKeyReleased(evt);
            }
        });

        txtresprate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtresprateKeyReleased(evt);
            }
        });

        jdate3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jdate3.setText("Respiratory rate:");

        jappointid1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jappointid1.setText("Heart rate:");

        txtheartrate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtheartrateKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)
                        .addGap(34, 34, 34)
                        .addComponent(bttnview))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jseats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpersonid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcarmodel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jmanufyear))
                        .addComponent(jmaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jinsurno, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jdiab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jaller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblpatientid, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addComponent(jappointid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151)
                                .addComponent(jdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addComponent(jdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtappointid)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(txtbloodpress)
                            .addComponent(txtresprate)
                            .addComponent(txtheartrate))
                        .addGap(37, 37, 37)
                        .addComponent(lblbloodpress, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcinsno, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldiab, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblall, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jappointid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(45, 45, 45))
                                    .addComponent(jdate3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(176, 176, 176)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblresprate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblheartrate, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(bttnaddappoint, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(bttnview))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpatientid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jappointid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jpersonid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtappointid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcarmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jmanufyear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdate, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtbloodpress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblbloodpress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jseats, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtresprate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblresprate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jappointid1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtheartrate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblheartrate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bttnaddappoint)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jinsurno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcinsno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdiab, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldiab, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jaller, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblall, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnaddappointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnaddappointActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblpersondetails.getSelectedRow();
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to convert details");
            return;
        }
        
        if(txtappointid.getText().length()<=0 || txtbloodpress.getText().length()<=0 || txtresprate.getText().length()<=0 || 
                txtheartrate.getText().length()<=0  ){
            JOptionPane.showMessageDialog(this, "Any field is left blank!");
        }
        else{
//            DefaultTableModel model = (DefaultTableModel) tblpersondetails.getModel();
//            CarInfo selectedCarDetails = (CarInfo) model.getValueAt(selectedRowIndex, 0);
//        
//            history.deleteCarDetails(selectedCarDetails);       
//            populateTable();
        
            String id = lblpatientid.getText();
            String appontid = txtappointid.getText();
            Date appointdate = jDateChooser1.getDate();
            int bloodpress = Integer.parseInt(txtbloodpress.getText());
            int resppress = Integer.parseInt(txtresprate.getText());
            int heartrate = Integer.parseInt(txtheartrate.getText());
            
            Encounter e = encounterhistory.addNewEncounter();
            
            e.setPatientID(id);
            e.setAppointid(appontid);
            e.setDatetime(appointdate);
            e.setBloodpress(bloodpress);
            e.setHeartrate(heartrate);
            e.setResprate(resppress);
            

           
        
            JOptionPane.showMessageDialog(this, "Appointment Booked!");
            
            
            lblpatientid.setText("");
            jDateChooser1.setDate(null);
            txtappointid.setText("");
            txtbloodpress.setText("");
            txtresprate.setText("");
            txtheartrate.setText("");
            
        }
        
        
    }//GEN-LAST:event_bttnaddappointActionPerformed

    private void bttnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnviewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblpersondetails.getSelectedRow();
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to View");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblpersondetails.getModel();
        CarInfo selectedCarDetails = (CarInfo) model.getValueAt(selectedRowIndex, 0);
        
        
        lblpatientid.setText(selectedCarDetails.getPersonid());
        lblname.setText(selectedCarDetails.getName());
        lbladdress.setText(String.valueOf(selectedCarDetails.getAddress()));
        lblage.setText(String.valueOf(selectedCarDetails.getAge()));
        lblgender.setText(selectedCarDetails.getGender());
        lblcommunity.setText(selectedCarDetails.getCommunity());
        lblcity.setText(selectedCarDetails.getCity());
        
        DefaultTableModel pmodel = (DefaultTableModel) tblpatientdetails.getModel();
        Patient pa = (Patient)pmodel.getValueAt(selectedRowIndex, 0);
        
        lblcinsno.setText(String.valueOf(pa.getInsuranceno()));
        lbldiab.setText(pa.getDiabetics());
        lblall.setText(pa.getAllergy());
    }//GEN-LAST:event_bttnviewActionPerformed

    private void bttnaddappointMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnaddappointMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bttnaddappointMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbloodpressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbloodpressKeyReleased
        // TODO add your handling code here:
        String PAT = "^[0-9]{0,3}$";
        Pattern pat = Pattern.compile(PAT);
        Matcher m = pat.matcher(txtbloodpress.getText());
        if(m.matches()){
            lblbloodpress.setText(null);
            bttnaddappoint.setEnabled(true);
        }
        else{
            lblbloodpress.setText("Invalid Entry");
            bttnaddappoint.setEnabled(false);
            
        }
    }//GEN-LAST:event_txtbloodpressKeyReleased

    private void txtresprateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtresprateKeyReleased
        // TODO add your handling code here:
        String PAT = "^[0-9]{0,3}$";
        Pattern pat = Pattern.compile(PAT);
        Matcher m = pat.matcher(txtresprate.getText());
        if(m.matches()){
            lblresprate.setText(null);
            bttnaddappoint.setEnabled(true);
        }
        else{
            lblresprate.setText("Invalid Entry");
            bttnaddappoint.setEnabled(false);
            
        }
    }//GEN-LAST:event_txtresprateKeyReleased

    private void txtheartrateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtheartrateKeyReleased
        // TODO add your handling code here:
        String PAT = "^[0-9]{0,3}$";
        Pattern pat = Pattern.compile(PAT);
        Matcher m = pat.matcher(txtheartrate.getText());
        if(m.matches()){
            lblheartrate.setText(null);
            bttnaddappoint.setEnabled(true);
        }
        else{
            lblheartrate.setText("Invalid Entry");
            bttnaddappoint.setEnabled(false);
            
        }
    }//GEN-LAST:event_txtheartrateKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnaddappoint;
    private javax.swing.JButton bttnview;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jaller;
    private javax.swing.JLabel jappointid;
    private javax.swing.JLabel jappointid1;
    private javax.swing.JLabel jcarmodel;
    private javax.swing.JLabel jcity;
    private javax.swing.JLabel jdate;
    private javax.swing.JLabel jdate1;
    private javax.swing.JLabel jdate3;
    private javax.swing.JLabel jdiab;
    private javax.swing.JLabel jinsurno;
    private javax.swing.JLabel jlocation;
    private javax.swing.JLabel jmaintenance;
    private javax.swing.JLabel jmanufyear;
    private javax.swing.JLabel jpersonid;
    private javax.swing.JLabel jseats;
    private javax.swing.JLabel jviewtitle;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblall;
    private javax.swing.JLabel lblbloodpress;
    private javax.swing.JLabel lblcinsno;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblcommunity;
    private javax.swing.JLabel lbldiab;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblheartrate;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpatientid;
    private javax.swing.JLabel lblresprate;
    private javax.swing.JTable tblpatientdetails;
    private javax.swing.JTable tblpersondetails;
    private javax.swing.JTextField txtappointid;
    private javax.swing.JTextField txtbloodpress;
    private javax.swing.JTextField txtheartrate;
    private javax.swing.JTextField txtresprate;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblpersondetails.getModel();
        model.setRowCount(0);
        
        for(CarInfo ci : history.getHistory()){
            
            Object[] row = new Object[7];
            row[0] = ci;
            row[1] = ci.getName();
            row[2] = ci.getAddress();
            row[3] = ci.getAge();
            row[4] = ci.getGender();
            row[5] = ci.getCommunity();
            row[6] = ci.getCity();
            
            
        model.addRow(row);
        }
        DefaultTableModel pmodel = (DefaultTableModel) tblpatientdetails.getModel();
        pmodel.setRowCount(0);
        
        for(Patient p : patienthistory.getPatienthistory()){
            
            Object[] row = new Object[4];
            row[0] = p;
            row[1] = p.getInsuranceno();
            row[2] = p.getDiabetics();
            row[3] = p.getAllergy();
            
            
            
        pmodel.addRow(row);
        }
    }

   
    
    
    
}

    

   
