/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;



import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.CarInfo;
import model.CarsHistory;

/**
 *
 * @author Admin
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    CarsHistory history;
    public String main_expired;
    public String car_available;
    
    
    
    public CreateJPanel(CarsHistory history) {
        initComponents();
        this.history = history;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcreatetitle = new javax.swing.JLabel();
        jname = new javax.swing.JLabel();
        jaddress = new javax.swing.JLabel();
        jage = new javax.swing.JLabel();
        jcommunity = new javax.swing.JLabel();
        jgender = new javax.swing.JLabel();
        combocommunity = new javax.swing.JComboBox<>();
        txtname = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        combogender1 = new javax.swing.JCheckBox();
        combogender2 = new javax.swing.JCheckBox();
        combogender3 = new javax.swing.JCheckBox();
        Save = new javax.swing.JButton();
        lbladdress = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblcolor = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        jpersonid = new javax.swing.JLabel();
        txtpersonid = new javax.swing.JTextField();
        jcity = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        lblcity = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jcreatetitle.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jcreatetitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jcreatetitle.setText("Fill Person Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcreatetitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jcreatetitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jname.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jname.setText("Name:");

        jaddress.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jaddress.setText("Address");

        jage.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jage.setText("Age");

        jcommunity.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jcommunity.setText("Community:");

        jgender.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jgender.setText("Gender:");

        combocommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "02215 Community 1", "02215 Community 2" }));
        combocommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocommunityActionPerformed(evt);
            }
        });

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        txtaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaddressKeyReleased(evt);
            }
        });

        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtageKeyReleased(evt);
            }
        });

        combogender1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combogender1.setText("Male");
        combogender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogender1ActionPerformed(evt);
            }
        });

        combogender2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combogender2.setText("Female");
        combogender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogender2ActionPerformed(evt);
            }
        });

        combogender3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combogender3.setText("Others");
        combogender3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogender3ActionPerformed(evt);
            }
        });

        Save.setFont(new java.awt.Font("Sitka Subheading", 0, 12)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        lbladdress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbladdressKeyReleased(evt);
            }
        });

        jpersonid.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jpersonid.setText("Person ID:");

        txtpersonid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonidActionPerformed(evt);
            }
        });
        txtpersonid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpersonidKeyReleased(evt);
            }
        });

        jcity.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jcity.setText("City:");

        txtcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcityKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jgender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpersonid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combocommunity, 0, 325, Short.MAX_VALUE)
                            .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(txtaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(txtage, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combogender1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(combogender2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combogender3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtpersonid, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(txtcity))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbladdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblcolor, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(lblage, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(lblcity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(Save)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpersonid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpersonid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combocommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jgender, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combogender1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combogender2)
                            .addComponent(combogender3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Save)
                .addGap(0, 237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combocommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocommunityActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_combocommunityActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String personid = txtpersonid.getText();
        
        if (combogender1.isSelected()){
            main_expired = combogender1.getText();
        }
        else if (combogender2.isSelected()){
            main_expired = combogender2.getText();
        }
        
        else if (combogender3.isSelected()){
            main_expired = combogender3.getText();
        }
        
        for (CarInfo ci : history.getHistory()){
            if(ci.getPersonid().contains(personid)){
                JOptionPane.showMessageDialog(this, "Person ID already exists!");
                return;
            }
            else
                break;
        }
        
        
        if(txtname.getText().length()<=0 || txtaddress.getText().length()<=0 || 
                txtage.getText().length()<=0 || txtpersonid.getText().length()<=0 || txtcity.getText().length()<=0){
            JOptionPane.showMessageDialog(this, "Any field is left blank!");
            
            
        }
        else{
            String id = txtpersonid.getText();
            String location = combocommunity.getSelectedItem().toString();
            String name = txtname.getText();
            String address = txtaddress.getText();
            String city = txtcity.getText();
            int age = Integer.parseInt(txtage.getText());
            
            
            
            CarInfo ci = history.addNewCarDetails();
        
            ci.setName(name);
            ci.setAddress(address);
            ci.setAge(age);
            ci.setPersonid(id);
            ci.setCommunity(location);
            ci.setCity(city);
            ci.setGender(main_expired);
            
           JOptionPane.showMessageDialog(this, "New Person Details Added!"); 
           txtname.setText("");
           txtaddress.setText("");
           txtage.setText("");
           txtpersonid.setText("");
           txtcity.setText("");
           combogender1.setSelected(false);
           combogender2.setSelected(false);
           combogender3.setSelected(false);
           
           combocommunity.setSelectedItem("02215 Community 1");
        }
        
        
        
        // setting everything blank
        
    }//GEN-LAST:event_SaveActionPerformed

    private void combogender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogender2ActionPerformed
        // TODO add your handling code here:
        if (combogender2.isSelected()){
            combogender1.setSelected(false);
            combogender3.setSelected(false);
        }
    }//GEN-LAST:event_combogender2ActionPerformed

    private void combogender3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogender3ActionPerformed
        // TODO add your handling code here:
        if (combogender3.isSelected()){
            combogender1.setSelected(false);
            combogender2.setSelected(false);
        }
    }//GEN-LAST:event_combogender3ActionPerformed

    private void lbladdressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbladdressKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbladdressKeyReleased

    private void txtaddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddressKeyReleased
        // TODO add your handling code here:
        String PAT = "^[A-Za-z0-9 ,.A-Za-z0-9]{0,50}$";
        Pattern pat = Pattern.compile(PAT);
        Matcher m = pat.matcher(txtaddress.getText());
        if(m.matches()){
            lbladdress.setText(null);
            Save.setEnabled(true);
        }
        else{
            lbladdress.setText("Invalid entry!");
            Save.setEnabled(false);
            
        }
    }//GEN-LAST:event_txtaddressKeyReleased

    private void txtageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyReleased
        // TODO add your handling code here:
        String PAT = "^[0-9]{0,3}$";
        Pattern pat = Pattern.compile(PAT);
        Matcher m = pat.matcher(txtage.getText());
        if(m.matches()){
            lblage.setText(null);
            Save.setEnabled(true);
        }
        else{
            lblage.setText("Invalid Entry!");
            Save.setEnabled(false);
        }
    }//GEN-LAST:event_txtageKeyReleased

    private void combogender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogender1ActionPerformed
        // TODO add your handling code here:
        if (combogender1.isSelected()){
            combogender2.setSelected(false);
            combogender3.setSelected(false);
        }
    }//GEN-LAST:event_combogender1ActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
        String PAT = "^[A-Za-z]{0,30}$";
        Pattern pat = Pattern.compile(PAT);
        Matcher m = pat.matcher(txtname.getText());
        if(m.matches()){
            lblname.setText(null);
            Save.setEnabled(true);
        }
        else{
            lblname.setText("Invalid entry");
            Save.setEnabled(false);
        }
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtpersonidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonidActionPerformed

    private void txtpersonidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpersonidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonidKeyReleased

    private void txtcityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcityKeyReleased
        // TODO add your handling code here:
        String PAT = "^[A-Za-z]{0,30}$";
        Pattern pat = Pattern.compile(PAT);
        Matcher m = pat.matcher(txtcity.getText());
        if(m.matches()){
            lblcity.setText(null);
            Save.setEnabled(true);
        }
        else{
            lblcity.setText("Invalid entry");
            Save.setEnabled(false);
        }
    }//GEN-LAST:event_txtcityKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JComboBox<String> combocommunity;
    private javax.swing.JCheckBox combogender1;
    private javax.swing.JCheckBox combogender2;
    private javax.swing.JCheckBox combogender3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jaddress;
    private javax.swing.JLabel jage;
    private javax.swing.JLabel jcity;
    private javax.swing.JLabel jcommunity;
    private javax.swing.JLabel jcreatetitle;
    private javax.swing.JLabel jgender;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jpersonid;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblcolor;
    private javax.swing.JLabel lblname;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpersonid;
    // End of variables declaration//GEN-END:variables
}
