/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.AbnormalPatientHistory;
import model.CarsHistory;
import model.EncounterHistory;
import model.PatientHistory;


/**
 *
 * @author Admin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    CarsHistory history;
    EncounterHistory encounterhistory;
    PatientHistory patienthistory;
    AbnormalPatientHistory abnormalhistory;
    
    public MainJFrame() {
        initComponents();
        
        //initialize 
        history = new CarsHistory();
        encounterhistory = new EncounterHistory();
        patienthistory = new PatientHistory();
        abnormalhistory = new AbnormalPatientHistory();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        bCreate = new javax.swing.JButton();
        bView = new javax.swing.JButton();
        bttnaddpatient = new javax.swing.JButton();
        bappointment = new javax.swing.JButton();
        bttnviewpatient = new javax.swing.JButton();
        bttnaddappoint = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(255, 153, 51));

        bCreate.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        bCreate.setText("Create");
        bCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreateActionPerformed(evt);
            }
        });

        bView.setFont(new java.awt.Font("Sitka Subheading", 0, 12)); // NOI18N
        bView.setText("Display");
        bView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bViewActionPerformed(evt);
            }
        });

        bttnaddpatient.setFont(new java.awt.Font("Sitka Subheading", 0, 12)); // NOI18N
        bttnaddpatient.setText("Add Person as Patient");
        bttnaddpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnaddpatientActionPerformed(evt);
            }
        });

        bappointment.setFont(new java.awt.Font("Sitka Subheading", 0, 12)); // NOI18N
        bappointment.setText("View Doctor Appointment");
        bappointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bappointmentActionPerformed(evt);
            }
        });

        bttnviewpatient.setFont(new java.awt.Font("Sitka Subheading", 0, 12)); // NOI18N
        bttnviewpatient.setText("View Patient Details");
        bttnviewpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnviewpatientActionPerformed(evt);
            }
        });

        bttnaddappoint.setFont(new java.awt.Font("Sitka Subheading", 0, 12)); // NOI18N
        bttnaddappoint.setText("Add Doctor Appointment");
        bttnaddappoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnaddappointActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Sitka Subheading", 0, 12)); // NOI18N
        jButton1.setText("View Comparison");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bttnaddappoint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(bttnviewpatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnaddpatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(bView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bappointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(bCreate)
                .addGap(34, 34, 34)
                .addComponent(bView)
                .addGap(39, 39, 39)
                .addComponent(bttnaddpatient)
                .addGap(43, 43, 43)
                .addComponent(bttnviewpatient)
                .addGap(36, 36, 36)
                .addComponent(bttnaddappoint)
                .addGap(38, 38, 38)
                .addComponent(bappointment)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateActionPerformed
        // TODO add your handling code here:
        
        CreateJPanel createPanel = new CreateJPanel(history);
        splitPane.setRightComponent(createPanel);
    }//GEN-LAST:event_bCreateActionPerformed

    private void bViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bViewActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewPanel = new ViewJPanel(history);
        splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_bViewActionPerformed

    private void bappointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bappointmentActionPerformed
        // TODO add your handling code here:
        ViewAppointment viewappoint = new ViewAppointment(history,encounterhistory,patienthistory);
        splitPane.setRightComponent(viewappoint);
        
    }//GEN-LAST:event_bappointmentActionPerformed

    private void bttnaddpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnaddpatientActionPerformed
        // TODO add your handling code here:
        AddNewPatient addpatient = new AddNewPatient (history, patienthistory);
        splitPane.setRightComponent(addpatient);
    }//GEN-LAST:event_bttnaddpatientActionPerformed

    private void bttnviewpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnviewpatientActionPerformed
        // TODO add your handling code here:
        ViewPatient viewpatient = new ViewPatient(history, patienthistory);
        splitPane.setRightComponent(viewpatient);
    }//GEN-LAST:event_bttnviewpatientActionPerformed

    private void bttnaddappointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnaddappointActionPerformed
        // TODO add your handling code here:
        AddNewAppointment addappoint = new AddNewAppointment(history,encounterhistory,patienthistory);
        splitPane.setRightComponent(addappoint);
    }//GEN-LAST:event_bttnaddappointActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Comparison comp = new Comparison(history,encounterhistory,patienthistory,abnormalhistory);
        splitPane.setRightComponent(comp);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreate;
    private javax.swing.JButton bView;
    private javax.swing.JButton bappointment;
    private javax.swing.JButton bttnaddappoint;
    private javax.swing.JButton bttnaddpatient;
    private javax.swing.JButton bttnviewpatient;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
