/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.CarInfo;
import model.CarsHistory;

/**
 *
 * @author Admin
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    CarsHistory history;
    static int count;
    
    public ViewJPanel(CarsHistory history) {
        initComponents();
        this.history = history;
        
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jviewtitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcardetails = new javax.swing.JTable();
        bttnview = new javax.swing.JButton();
        bttnupdate = new javax.swing.JButton();
        jmanufyear = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jseats = new javax.swing.JLabel();
        jmaintenance = new javax.swing.JLabel();
        jlocation = new javax.swing.JLabel();
        txtcommunity = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jcarmodel = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        lbladdress = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblcommunity = new javax.swing.JLabel();
        jpersonid = new javax.swing.JLabel();
        txtpersonid = new javax.swing.JTextField();
        jcity = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        jdelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 153));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        jviewtitle.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jviewtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jviewtitle.setText("View Person Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jviewtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jviewtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblcardetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Person ID", "Name", "Address", "Age", "Gender", "Community", "City"
            }
        ));
        jScrollPane1.setViewportView(tblcardetails);

        bttnview.setText("View");
        bttnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnviewActionPerformed(evt);
            }
        });

        bttnupdate.setText("Update");
        bttnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bttnupdateMousePressed(evt);
            }
        });
        bttnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnupdateActionPerformed(evt);
            }
        });

        jmanufyear.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jmanufyear.setText("Address:");

        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtageKeyReleased(evt);
            }
        });

        jseats.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jseats.setText("Age:");

        jmaintenance.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jmaintenance.setText("Gender:");

        jlocation.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jlocation.setText("Community:");

        txtcommunity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcommunityKeyReleased(evt);
            }
        });

        jcarmodel.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jcarmodel.setText("Name:");

        txtaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaddressKeyReleased(evt);
            }
        });

        txtgender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgenderKeyReleased(evt);
            }
        });

        jpersonid.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jpersonid.setText("Person ID:");

        txtpersonid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonidActionPerformed(evt);
            }
        });
        txtpersonid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpersonidKeyReleased(evt);
            }
        });

        jcity.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jcity.setText("City:");

        txtcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcityKeyReleased(evt);
            }
        });

        jdelete.setText("Delete");
        jdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jmaintenance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jseats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpersonid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcity)
                    .addComponent(txtpersonid)
                    .addComponent(txtcommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(txtaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(txtage, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblcommunity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(lblgender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbladdress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(670, 670, 670)
                .addComponent(bttnview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnupdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jdelete)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(204, 204, 204)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jcarmodel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jmanufyear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(639, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnview)
                    .addComponent(bttnupdate)
                    .addComponent(jdelete))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpersonid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpersonid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jseats, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jmaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jcity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(225, 225, 225))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(231, 231, 231)
                    .addComponent(jcarmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)
                    .addComponent(jmanufyear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(415, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnupdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblcardetails.getSelectedRow();
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to Update");
            return;
        }
        
        if(txtname.getText().length()<=0 || txtaddress.getText().length()<=0 || txtage.getText().length()<=0 || 
                txtcommunity.getText().length()<=0 || txtgender.getText().length()<=0 || txtpersonid.getText().length()<=0 || 
                txtcity.getText().length()<=0 ){
            JOptionPane.showMessageDialog(this, "Any field is left blank!");
            
            
        }
        else{
            DefaultTableModel model = (DefaultTableModel) tblcardetails.getModel();
            CarInfo selectedCarDetails = (CarInfo) model.getValueAt(selectedRowIndex, 0);
        
            history.deleteCarDetails(selectedCarDetails);       
            populateTable();
        
            String id = txtpersonid.getText();
            String name = txtname.getText();
            String address = txtaddress.getText();
            int seats = Integer.parseInt(txtage.getText());
            String community = txtcommunity.getText();
            String gender = txtgender.getText();
            String city = txtcity.getText();
        
            CarInfo ci = history.addNewCarDetails();
            
            ci.setPersonid(id);
            ci.setName(name);
            ci.setAddress(address);
            ci.setAge(seats);
            ci.setCommunity(community);
            ci.setGender(gender);
            ci.setCity(city);
        
            JOptionPane.showMessageDialog(this, "Person Details Updated!Select Display again to view Updated Details");
            
            txtpersonid.setText("");
            txtname.setText("");
            txtaddress.setText("");
            txtage.setText("");
            txtcommunity.setText("");
            txtgender.setText("");
            txtcity.setText("");
        }
        
        
    }//GEN-LAST:event_bttnupdateActionPerformed

    private void bttnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnviewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblcardetails.getSelectedRow();
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to View");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblcardetails.getModel();
        CarInfo selectedCarDetails = (CarInfo) model.getValueAt(selectedRowIndex, 0);
        
        
        txtpersonid.setText(selectedCarDetails.getPersonid());
        txtname.setText(selectedCarDetails.getName());
        txtaddress.setText(String.valueOf(selectedCarDetails.getAddress()));
        txtage.setText(String.valueOf(selectedCarDetails.getAge()));
        txtgender.setText(selectedCarDetails.getGender());
        txtcommunity.setText(selectedCarDetails.getCommunity());
        txtcity.setText(selectedCarDetails.getCity());
        
        
    }//GEN-LAST:event_bttnviewActionPerformed

    private void bttnupdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnupdateMousePressed
        // TODO add your handling code here:
        if(evt.getClickCount()>0){
            count = 1;
        }
    }//GEN-LAST:event_bttnupdateMousePressed

    private void txtaddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddressKeyReleased
        // TODO add your handling code here:
        String PAT = "^[A-Za-z0-9 ,.A-Za-z0-9]{0,50}$";
        Pattern pat = Pattern.compile(PAT);
        Matcher m = pat.matcher(txtaddress.getText());
        if(m.matches()){
            lbladdress.setText(null);
            bttnupdate.setEnabled(true);
        }
        else{
            lbladdress.setText("Invalid Entry!");
            bttnupdate.setEnabled(false);
            
        }
    }//GEN-LAST:event_txtaddressKeyReleased

    private void txtageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyReleased
        // TODO add your handling code here:
        String PAT = "^[0-9]{0,3}$";
        Pattern pat = Pattern.compile(PAT);
        Matcher m = pat.matcher(txtage.getText());
        if(m.matches()){
            lblname.setText(null);
            bttnupdate.setEnabled(true);
        }
        else{
            lblname.setText("Invalid Entry");
            bttnupdate.setEnabled(false);
            
        }
    }//GEN-LAST:event_txtageKeyReleased

    private void txtgenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgenderKeyReleased
        // TODO add your handling code here:
        String PAT = "^(Male|male|female|Female|Others|others)$";
        Pattern pat = Pattern.compile(PAT);
        Matcher m = pat.matcher(txtgender.getText());
        if(m.matches()){
            lblgender.setText(null);
            bttnupdate.setEnabled(true);
        }
        else{
            lblgender.setText("Invalid Entry");
            bttnupdate.setEnabled(false);
        }
        
    }//GEN-LAST:event_txtgenderKeyReleased

    private void txtcommunityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcommunityKeyReleased
        // TODO add your handling code here:
        String PAT = "^(02215 Community 1|02215 community 1|02215 Community 2|02215 community 2)$";
        Pattern pat = Pattern.compile(PAT);
        Matcher m = pat.matcher(txtcommunity.getText());
        if(m.matches()){
            lblcommunity.setText(null);
            bttnupdate.setEnabled(true);
        }
        else{
            lblcommunity.setText("Invalid entry!");
            bttnupdate.setEnabled(false);
            
        }
    }//GEN-LAST:event_txtcommunityKeyReleased

    private void txtpersonidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonidActionPerformed

    private void txtpersonidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpersonidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonidKeyReleased

    private void txtcityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcityKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityKeyReleased

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblcardetails.getSelectedRow();
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to Delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblcardetails.getModel();
        CarInfo selectedCarDetails = (CarInfo) model.getValueAt(selectedRowIndex, 0);
        
        history.deleteCarDetails(selectedCarDetails);       
        populateTable();
    }//GEN-LAST:event_jdeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnupdate;
    private javax.swing.JButton bttnview;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jcarmodel;
    private javax.swing.JLabel jcity;
    private javax.swing.JButton jdelete;
    private javax.swing.JLabel jlocation;
    private javax.swing.JLabel jmaintenance;
    private javax.swing.JLabel jmanufyear;
    private javax.swing.JLabel jpersonid;
    private javax.swing.JLabel jseats;
    private javax.swing.JLabel jviewtitle;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblcommunity;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblname;
    private javax.swing.JTable tblcardetails;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcommunity;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpersonid;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblcardetails.getModel();
        model.setRowCount(0);
        
        for(CarInfo ci : history.getHistory()){
            
            Object[] row = new Object[7];
            row[0] = ci;
            row[1] = ci.getName();
            row[2] = ci.getAddress();
            row[3] = ci.getAge();
            row[4] = ci.getGender();
            row[5] = ci.getCommunity();
            row[6] = ci.getCity();
            
            
        model.addRow(row);
        }
        
    }

   
    
    
    
}

    

   
