/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.CarInfo;
import model.CarsHistory;
import model.Encounter;
import model.EncounterHistory;
import model.Patient;
import model.PatientHistory;

/**
 *
 * @author Admin
 */
public class ViewAppointment extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    CarsHistory history;
    PatientHistory patienthistory;
    EncounterHistory encounterhistory;
    
    public ViewAppointment(CarsHistory history,EncounterHistory encounterhistory ,PatientHistory patienthistory) {
        initComponents();
        this.history = history;
        this.patienthistory = patienthistory;
        this.encounterhistory = encounterhistory;
        
        //populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jviewtitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpersondetails = new javax.swing.JTable();
        bttnview = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpatientdetails = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblappointments = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 153));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        jviewtitle.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jviewtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jviewtitle.setText("View Appointment Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jviewtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jviewtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblpersondetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Person ID", "Name", "Address", "Age", "Gender", "Community", "City"
            }
        ));
        jScrollPane1.setViewportView(tblpersondetails);

        bttnview.setText("View Appointment");
        bttnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnviewActionPerformed(evt);
            }
        });

        jButton1.setText("All Patients");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblpatientdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Insurance No.", "Diabetic", "Allergy"
            }
        ));
        jScrollPane2.setViewportView(tblpatientdetails);

        tblappointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Appointment ID", "Appointment Date", "Blood Pressure", "Heart Rate", "Respiratory Rate"
            }
        ));
        jScrollPane3.setViewportView(tblappointments);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(bttnview))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnview)
                    .addComponent(jButton1))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnviewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblpersondetails.getSelectedRow();
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a patient to see appointments and vital signs!");
            
        }
        else{
            DefaultTableModel pmodel = (DefaultTableModel) tblpersondetails.getModel();
            String patientid = pmodel.getValueAt(selectedRowIndex, 0).toString();
            
            DefaultTableModel amodel = (DefaultTableModel) tblappointments.getModel();
            amodel.setRowCount(0);
            
            for (Encounter e : encounterhistory.getEncounterHistory()){
                if(e.getPatientID()==patientid){
                    Object[] row = new Object[6];
                    row[0] = e;
                    row[1] = e.getAppointid();
                    row[2] = e.getDatetime();
                    row[3] = e.getBloodpress();
                    row[4] = e.getHeartrate();
                    row[5] = e.getResprate();
                    
            amodel.addRow(row);
                    
                }
            }
        }
        
        
        
        
    }//GEN-LAST:event_bttnviewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnview;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jviewtitle;
    private javax.swing.JTable tblappointments;
    private javax.swing.JTable tblpatientdetails;
    private javax.swing.JTable tblpersondetails;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblpersondetails.getModel();
        model.setRowCount(0);
        
        for(CarInfo ci : history.getHistory()){
            
            Object[] row = new Object[7];
            row[0] = ci;
            row[1] = ci.getName();
            row[2] = ci.getAddress();
            row[3] = ci.getAge();
            row[4] = ci.getGender();
            row[5] = ci.getCommunity();
            row[6] = ci.getCity();
            
            
        model.addRow(row);
        }
        DefaultTableModel pmodel = (DefaultTableModel) tblpatientdetails.getModel();
        pmodel.setRowCount(0);
        
        for(Patient p : patienthistory.getPatienthistory()){
            
            Object[] row = new Object[4];
            row[0] = p;
            row[1] = p.getInsuranceno();
            row[2] = p.getDiabetics();
            row[3] = p.getAllergy();
            
            
            
        pmodel.addRow(row);
        }
    }

   
    
    
    
}

    

   
